---
apiVersion: v1
kind: Service
metadata:
  name: "envoy-admin-${project.artifactId}"
  labels:
    expose: "true"
spec:
  ports:
  - name: envoy-admin
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    project: sb-webmvc-envoy
    provider: fabric8
    group: org.workspace7.msa
