---
apiVersion: v1
kind: Service
spec:
  ports:
  - name: http2
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    project: sb-webmvc-envoy
    provider: fabric8
    group: org.workspace7.msa
